language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jfrancisco777/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jfrancisco777/react-test yarn test

after_success:
  - docker build -t jfrancisco777/multi-client ./client
  - docker build -t jfrancisco777/multi-nginx ./nginx
  - docker build -t jfrancisco777/multi-server ./server
  - docker build -t jfrancisco777/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jfrancisco777/multi-client
  - docker push jfrancisco777/multi-nginx
  - docker push jfrancisco777/multi-server
  - docker push jfrancisco777/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "arn:aws:s3:::elasticbeanstalk-us-east-1-638337117025"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
